[package]
name = "dynboard-gen"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.37", features = ["derive"] }
rand = "0.9.1"
reqwest = "0.12.15"
tokio = { version = "1.45.0", features = ["macros", "rt-multi-thread"] }
opencv = "0.94.4"
